### ISSUE TITLE
Add Docker to run entire project

### ISSUE THREAD

**Issue by frandelgado** [Xivis/faucy#12]

**Comment by frandelgado** [comment]
@lndgalante The only thing that worries me about this is that if we implement docker as a dev environment improvement we lose in dev/prod parity since prod will still be running in heroku

**Comment by lndgalante** [comment]
@frandelgado yes we're going to use Docker only on development mode to avoid running all install and run commands manually like we did with Agustin. Also the frontend is hosted on Fleek (similar to Netlify but with IPFS distribution) and also doesn't support Docker.
