### ISSUE TITLE
Create bot to market Faucy

### ISSUE THREAD

**Issue by lndgalante** [Xivis/faucy#29]
Bot de Twitter que detecte los hashtags #Rinkeby por ej y le contestemos con algo así:
“Hi [TWITTER_HANDLE] :hola: We’re developing Faucy to get ethers from any testnet easily! You can reach us through @wearexivis or telegram. https://faucy.dev”

**Comment by ragonzal** [comment]
Work in progress https://github.com/Xivis/faucy-twitter-bot 🚀
